### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by nilutz** [SmartDataAnalytics/MA-INF-4222-NLP-Lab#45]
Hi,
do you want any specific folder structure for uploading the tasks (SoSe18)? Like so?:
```
.
+-- 2018_SoSe
|   +-- Task1
|   +-- Task2
|   +-- Task3
+--2017_SoSe
+--2017-18_WiSe
```

**Comment by torayeff** [comment]
+1

**Comment by torayeff** [comment]
How should we submit now? Do we have any permissions to upload files to this repo?

**Comment by diegoesteves** [comment]
hey guys, thanks for your comments: I've just updated the documentation regarding this. Please see: 
https://github.com/SmartDataAnalytics/MA-INF-4222-NLP-Lab

short: \<semester>\exercises\<student_id>\<file_name> where <file_name> in (task_1.py, task_2.py, etc..)

**Comment by diegoesteves** [comment]
submissions should be done through pull request :-)
